# This must be created before the deployment in which it is referenced
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: my-namespace
type: Opaque
data: 
    mongo-root-username: dXNlcm5hbWU=   # echo -n 'username' | base64
    mong0-root-password: cGFzc3dvcmQ=   # echo -n 'password' | base64
  